weights: ''
cfg: cfg/yolor_p6.cfg
data: ./data/cell.yaml
hyp: ./data/hyp.scratch.640.yaml
epochs: 200
batch_size: 16
img_size:
- 512
- 512
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: '0'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
log_imgs: 16
workers: 8
project: runs/train
name: yolor_p6
exist_ok: false
total_batch_size: 16
world_size: 1
global_rank: -1
save_dir: runs/train/yolor_p6
