server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: capstone-apigateway-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    gateway:
      routes:
        - id: capstone-user-service
          uri: lb://CAPSTONE-USER-SERVICE
          predicates:
            - Path=/capstone-user-service/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/capstone-user-service/(?<segment>.*), /$\{segment}
        - id: capstone-user-service
          uri: lb://CAPSTONE-USER-SERVICE
          predicates:
            - Path=/capstone-user-service/images
            - Method=POST, DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/capstone-user-service/(?<segment>.*), /$\{segment}
        - id: capstone-user-service
          uri: lb://CAPSTONE-USER-SERVICE
          predicates:
            - Path=/capstone-user-service/url/images
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/capstone-user-service/(?<segment>.*), /$\{segment}
        - id: capstone-user-service
          uri: lb://CAPSTONE-USER-SERVICE
          predicates:
            - Path=/capstone-user-service/users
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/capstone-user-service/(?<segment>.*), /$\{segment}
        - id: capstone-user-service
          uri: lb://CAPSTONE-USER-SERVICE
          predicates:
            - Path=/capstone-user-service/**
            - Method=GET, DELETE, PUT
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/capstone-user-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: capstone-user-service
          uri: lb://CAPSTONE-USER-SERVICE
          predicates:
            - Path=/capstone-user-service/actuator/**
            - Method=GET, POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/capstone-user-service/(?<segment>.*), /$\{segment}
        - id: capstone-cell-service
          uri: lb://CAPSTONE-CELL-SERVICE
          predicates:
            - Path=/capstone-cell-service/**
            - Method=GET, POST, DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/capstone-cell-service/(?<segment>.*), /$\{segment}
#            - AuthorizationHeaderFilter

management:
  endpoint:
    web:
      exposure:
        include: refresh, httptrace, busrefresh
